-- REST||ART INTEGRACE - release v1.1 import
-- 1) Nahraj ZIP na server, uprav cestu /storage/rest_art/releases/v1_1/ podle reality.
-- 2) Spust v phpMyAdmin nad správnou databází.
SET NAMES utf8mb4;
START TRANSACTION;
UPDATE rest_art_document_releases SET status = 'archived' WHERE release_code IN ('REST_ART_FINAL_FORMS_RELEASE','REST_ART_FINAL_FORMS_RELEASE_V1_0');
INSERT INTO rest_art_document_releases (release_code,title,version,file_name,file_path,file_type,status,description) VALUES ('REST_ART_FINAL_FORMS_RELEASE_V1_1','REST||ART finální provozní formuláře v1.1','v1.1','REST_ART_PROVOZNI_FORMULARE_RELEASE_v1_1.zip','/storage/rest_art/releases/REST_ART_PROVOZNI_FORMULARE_RELEASE_v1_1.zip','zip','active','Finální provozní release formulářů REST||ART INTEGRACE včetně JAILBREAK dotazníku, ID formulářů a GDPR souborů s čárovými kódy.');
SET @release_id := LAST_INSERT_ID();
INSERT INTO rest_art_document_files (release_id,category_code,category_title,document_code,title,version,file_name,file_path,file_type,is_fillable,is_all_in_one,sensitivity,status,crm_use,reporting_export,notes,sort_order) VALUES
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-001','Krycí list GDPR balíčku','v1.3','RAI-FRM-GDPR-001_KRYCI_LIST_GDPR_BALICKU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-001_KRYCI_LIST_GDPR_BALICKU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',1),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-002','Informační memorandum','v1.3','RAI-FRM-GDPR-002_INFORMACNI_MEMORANDUM_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-002_INFORMACNI_MEMORANDUM_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',2),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-003','Informovaný souhlas GDPR','v1.3','RAI-FRM-GDPR-003_INFORMOVANY_SOUHLAS_GDPR_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-003_INFORMOVANY_SOUHLAS_GDPR_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',3),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-004','Zvláštní kategorie údajů','v1.3','RAI-FRM-GDPR-004_ZVLASTNI_KATEGORIE_UDAJU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-004_ZVLASTNI_KATEGORIE_UDAJU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',4),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-005','Foto / video / audio souhlas','v1.3','RAI-FRM-GDPR-005_FOTO_VIDEO_AUDIO_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-005_FOTO_VIDEO_AUDIO_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',5),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-006','Příběh / citace / kazuistika','v1.3','RAI-FRM-GDPR-006_PRIBEH_CITACE_KAZUISTIKA_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-006_PRIBEH_CITACE_KAZUISTIKA_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',6),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-007','Sdílení údajů s partnery','v1.3','RAI-FRM-GDPR-007_SDILENI_UDAJU_S_PARTNERY_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-007_SDILENI_UDAJU_S_PARTNERY_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',7),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-008','Elektronická komunikace a follow-up','v1.3','RAI-FRM-GDPR-008_ELEKTRONICKA_KOMUNIKACE_FOLLOW_UP_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-008_ELEKTRONICKA_KOMUNIKACE_FOLLOW_UP_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',8),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-009','BOD ZLOMU - mladistvý / zákonný zástupce','v1.3','RAI-FRM-GDPR-009_BOD_ZLOMU_MLADISTVY_ZAKONNY_ZASTUPCE_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-009_BOD_ZLOMU_MLADISTVY_ZAKONNY_ZASTUPCE_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',9),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-010','Dobrovolník - osobní údaje','v1.3','RAI-FRM-GDPR-010_DOBROVOLNIK_OSOBNI_UDAJE_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-010_DOBROVOLNIK_OSOBNI_UDAJE_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',10),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-011','Pracovník / mentor - mlčenlivost','v1.3','RAI-FRM-GDPR-011_PRACOVNIK_MENTOR_MLCENLIVOST_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-011_PRACOVNIK_MENTOR_MLCENLIVOST_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',11),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-012','Partner / externí subjekt','v1.3','RAI-FRM-GDPR-012_PARTNER_EXTERNI_SUBJEKT_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-012_PARTNER_EXTERNI_SUBJEKT_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',12),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-013','Odvolání nebo omezení souhlasu','v1.3','RAI-FRM-GDPR-013_ODVOLANI_NEBO_OMEZENI_SOUHLASU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-013_ODVOLANI_NEBO_OMEZENI_SOUHLASU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',13),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-014','Žádost subjektu údajů','v1.3','RAI-FRM-GDPR-014_ZADOST_SUBJEKTU_UDAJU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-014_ZADOST_SUBJEKTU_UDAJU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',14),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-015','Záznam o incidentu','v1.3','RAI-FRM-GDPR-015_ZAZNAM_O_INCIDENTU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-015_ZAZNAM_O_INCIDENTU_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',15),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-016','Anonymizační a donor/export karta','v1.3','RAI-FRM-GDPR-016_ANONYMIZACNI_DONOR_EXPORT_KARTA_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-016_ANONYMIZACNI_DONOR_EXPORT_KARTA_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',16),
(@release_id,'01_GDPR_A_SOUHLASY','GDPR a souhlasy','RAI-FRM-GDPR-017','Archivace, skartace a přístupy','v1.3','RAI-FRM-GDPR-017_ARCHIVACE_SKARTACE_PRISTUPY_FILLABLE_v1_3_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-017_ARCHIVACE_SKARTACE_PRISTUPY_FILLABLE_v1_3_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'GDPR formulář s přiděleným ID a čárovým kódem',17),
(@release_id,'02_KLIENTSKA_SLOZKA','Klientská složka','RAI-FRM-KLI-001','Intake form','v1.5','RAI-FRM-KLI-001_INTAKE_FORM_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/02_KLIENTSKA_SLOZKA/RAI-FRM-KLI-001_INTAKE_FORM_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'',18),
(@release_id,'02_KLIENTSKA_SLOZKA','Klientská složka','RAI-FRM-KLI-002','Kniha klienta','v1.6','RAI-FRM-KLI-002_KNIHA_KLIENTA_FILLABLE_v1_6_COMPACT_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/02_KLIENTSKA_SLOZKA/RAI-FRM-KLI-002_KNIHA_KLIENTA_FILLABLE_v1_6_COMPACT_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'',19),
(@release_id,'02_KLIENTSKA_SLOZKA','Klientská složka','RAI-FRM-KLI-003','Exit form','v1.5','RAI-FRM-KLI-003_EXIT_FORM_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/02_KLIENTSKA_SLOZKA/RAI-FRM-KLI-003_EXIT_FORM_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'',20),
(@release_id,'09_PROGRAMOVE_PRILOHY','Programové přílohy','RAI-FRM-JB-001','JAILBREAK dotazník','v1.5','RAI-FRM-JB-001_JAILBREAK_DOTAZNIK_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/09_PROGRAMOVE_PRILOHY/RAI-FRM-JB-001_JAILBREAK_DOTAZNIK_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'Doplněno ve v1.1',21),
(@release_id,'03_INTERVENCE','Intervence','RAI-FRM-INT-001','Kniha intervencí','v1.5','RAI-FRM-INT-001_KNIHA_INTERVENCI_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/03_INTERVENCE/RAI-FRM-INT-001_KNIHA_INTERVENCI_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'',22),
(@release_id,'04_KRIZOVY_REZIM','Krizový režim','RAI-FRM-KRZ-001','Kniha krizových intervencí','v1.5','RAI-FRM-KRZ-001_KNIHA_KRIZOVYCH_INTERVENCI_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/04_KRIZOVY_REZIM/RAI-FRM-KRZ-001_KNIHA_KRIZOVYCH_INTERVENCI_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'restricted','active',1,0,'',23),
(@release_id,'04_KRIZOVY_REZIM','Krizový režim','RAI-FRM-KRZ-002','Krizový formulář','v1.5','RAI-FRM-KRZ-002_KRIZOVY_FORMULAR_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/04_KRIZOVY_REZIM/RAI-FRM-KRZ-002_KRIZOVY_FORMULAR_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'restricted','active',1,0,'Převedeno podle finálních pravidel v1.5',24),
(@release_id,'05_EVALUACE_A_FOLLOW_UP','Evaluace a follow-up','RAI-FRM-EVA-001','Stabilizační index','v1.5','RAI-FRM-EVA-001_STABILIZACNI_INDEX_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/05_EVALUACE_A_FOLLOW_UP/RAI-FRM-EVA-001_STABILIZACNI_INDEX_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,1,'Exportovat anonymizovaně',25),
(@release_id,'05_EVALUACE_A_FOLLOW_UP','Evaluace a follow-up','RAI-FRM-EVA-002','Follow-up tracking','v1.5','RAI-FRM-EVA-002_FOLLOW_UP_TRACKING_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/05_EVALUACE_A_FOLLOW_UP/RAI-FRM-EVA-002_FOLLOW_UP_TRACKING_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,1,'Exportovat anonymizovaně',26),
(@release_id,'07_ETIKA_A_TYM','Etika a tým','RAI-FRM-ETY-001','Mlčenlivost a etický závazek týmu','v1.5','RAI-FRM-ETY-001_MLCENLIVOST_ETICKY_ZAVAZEK_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/07_ETIKA_A_TYM/RAI-FRM-ETY-001_MLCENLIVOST_ETICKY_ZAVAZEK_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'',27),
(@release_id,'06_REGISTRY','Registry','RAI-FRM-REG-001','Registr dobrovolníků','v1.5','RAI-FRM-REG-001_REGISTR_DOBROVOLNIKU_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/06_REGISTRY/RAI-FRM-REG-001_REGISTR_DOBROVOLNIKU_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'Registry v1.7',28),
(@release_id,'06_REGISTRY','Registry','RAI-FRM-REG-002','Evidence komunitních aktivit','v1.5','RAI-FRM-REG-002_EVIDENCE_KOMUNITNICH_AKTIVIT_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/06_REGISTRY/RAI-FRM-REG-002_EVIDENCE_KOMUNITNICH_AKTIVIT_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'Registry v1.7',29),
(@release_id,'06_REGISTRY','Registry','RAI-FRM-REG-003','Registr partnerů','v1.5','RAI-FRM-REG-003_REGISTR_PARTNERU_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/06_REGISTRY/RAI-FRM-REG-003_REGISTR_PARTNERU_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'Registry v1.7',30),
(@release_id,'06_REGISTRY','Registry','RAI-FRM-REG-004','Registr rizik','v1.5','RAI-FRM-REG-004_REGISTR_RIZIK_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/06_REGISTRY/RAI-FRM-REG-004_REGISTR_RIZIK_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'Registry v1.7',31),
(@release_id,'06_REGISTRY','Registry','RAI-FRM-REG-005','Registr stížností','v1.5','RAI-FRM-REG-005_REGISTR_STIZNOSTI_FILLABLE_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/06_REGISTRY/RAI-FRM-REG-005_REGISTR_STIZNOSTI_FILLABLE_v1_5_CONTENT_LOCKED.pdf','pdf',1,0,'high','active',1,0,'Registry v1.7',32),
(@release_id,'99_ALL_IN_ONE_VOLITELNE','ALL-IN-ONE volitelné','RAI-AIO-REG-001','Registry ALL-IN-ONE','v1.7','RAI-AIO-REG-001_REGISTRY_ALL_IN_ONE_v1_7_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/99_ALL_IN_ONE_VOLITELNE/RAI-AIO-REG-001_REGISTRY_ALL_IN_ONE_v1_7_CONTENT_LOCKED.pdf','pdf',1,1,'internal','active',0,0,'Volitelný souhrnný PDF balík',33),
(@release_id,'08_DOPLNKOVE_LISTY','Doplňkové listy','RAI-FRM-DOP-001','List incidentů','v1.7','RAI-FRM-DOP-001_LIST_INCIDENTU_A4_LANDSCAPE_FILLABLE_v1_7_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/08_DOPLNKOVE_LISTY/RAI-FRM-DOP-001_LIST_INCIDENTU_A4_LANDSCAPE_FILLABLE_v1_7_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'Doplňkový A4 landscape list',34),
(@release_id,'08_DOPLNKOVE_LISTY','Doplňkové listy','RAI-FRM-DOP-002','List hranic podpory','v1.7','RAI-FRM-DOP-002_LIST_HRANIC_PODPORY_A4_LANDSCAPE_FILLABLE_v1_7_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/08_DOPLNKOVE_LISTY/RAI-FRM-DOP-002_LIST_HRANIC_PODPORY_A4_LANDSCAPE_FILLABLE_v1_7_CONTENT_LOCKED.pdf','pdf',1,0,'internal','active',1,0,'Doplňkový A4 landscape list',35),
(@release_id,'99_ALL_IN_ONE_VOLITELNE','ALL-IN-ONE volitelné','RAI-AIO-DOP-001','Doplňkové listy ALL-IN-ONE','v1.7','RAI-AIO-DOP-001_DOPLNKOVE_LISTY_INCIDENTY_HRANICE_ALL_IN_ONE_v1_7_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/99_ALL_IN_ONE_VOLITELNE/RAI-AIO-DOP-001_DOPLNKOVE_LISTY_INCIDENTY_HRANICE_ALL_IN_ONE_v1_7_CONTENT_LOCKED.pdf','pdf',1,1,'internal','active',0,0,'Volitelný souhrnný PDF balík',36),
(@release_id,'10_METODIKY_A_PODKLADY','Metodiky a podklady','RAI-DOC-PROJ-001','One-page projektu','v1.5','RAI-DOC-PROJ-001_ONE_PAGE_PROJEKT_2026_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/10_METODIKY_A_PODKLADY/RAI-DOC-PROJ-001_ONE_PAGE_PROJEKT_2026_v1_5_CONTENT_LOCKED.pdf','pdf',0,0,'public','active',0,1,'Veřejný/partnerský podklad',37),
(@release_id,'10_METODIKY_A_PODKLADY','Metodiky a podklady','RAI-MET-JB-001','Metodika JAILBREAK','v1.5','RAI-MET-JB-001_METODIKA_JAILBREAK_v1_5_CONTENT_LOCKED.pdf','/storage/rest_art/releases/v1_1/10_METODIKY_A_PODKLADY/RAI-MET-JB-001_METODIKA_JAILBREAK_v1_5_CONTENT_LOCKED.pdf','pdf',0,0,'internal','active',0,0,'Metodický podklad',38);
COMMIT;