-- REST||ART release barcode v1.2 import
-- Before import, create a release row in rest_art_document_releases or set @release_id manually.
SET @release_id := (SELECT id FROM rest_art_document_releases WHERE release_code = 'REST_ART_FINAL_FORMS_RELEASE_V1_2_BARCODE' ORDER BY id DESC LIMIT 1);


INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-001',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-001',
  'Krycí list GDPR balíčku',
  'v1.3',
  'RAI-FRM-GDPR-001_KRYCI_LIST_GDPR_BALICKU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-001_KRYCI_LIST_GDPR_BALICKU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  1
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-002',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-002',
  'Informační memorandum',
  'v1.3',
  'RAI-FRM-GDPR-002_INFORMACNI_MEMORANDUM_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-002_INFORMACNI_MEMORANDUM_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  2
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-003',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-003',
  'Informovaný souhlas GDPR',
  'v1.3',
  'RAI-FRM-GDPR-003_INFORMOVANY_SOUHLAS_GDPR_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-003_INFORMOVANY_SOUHLAS_GDPR_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  3
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-004',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-004',
  'Zvláštní kategorie údajů',
  'v1.3',
  'RAI-FRM-GDPR-004_ZVLASTNI_KATEGORIE_UDAJU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-004_ZVLASTNI_KATEGORIE_UDAJU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  4
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-005',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-005',
  'Foto / video / audio souhlas',
  'v1.3',
  'RAI-FRM-GDPR-005_FOTO_VIDEO_AUDIO_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-005_FOTO_VIDEO_AUDIO_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  5
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-006',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-006',
  'Příběh / citace / kazuistika',
  'v1.3',
  'RAI-FRM-GDPR-006_PRIBEH_CITACE_KAZUISTIKA_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-006_PRIBEH_CITACE_KAZUISTIKA_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  6
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-007',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-007',
  'Sdílení údajů s partnery',
  'v1.3',
  'RAI-FRM-GDPR-007_SDILENI_UDAJU_S_PARTNERY_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-007_SDILENI_UDAJU_S_PARTNERY_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  7
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-008',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-008',
  'Elektronická komunikace a follow-up',
  'v1.3',
  'RAI-FRM-GDPR-008_ELEKTRONICKA_KOMUNIKACE_FOLLOW_UP_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-008_ELEKTRONICKA_KOMUNIKACE_FOLLOW_UP_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  8
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-009',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-009',
  'BOD ZLOMU - mladistvý / zákonný zástupce',
  'v1.3',
  'RAI-FRM-GDPR-009_BOD_ZLOMU_MLADISTVY_ZAKONNY_ZASTUPCE_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-009_BOD_ZLOMU_MLADISTVY_ZAKONNY_ZASTUPCE_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  9
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-010',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-010',
  'Dobrovolník - osobní údaje',
  'v1.3',
  'RAI-FRM-GDPR-010_DOBROVOLNIK_OSOBNI_UDAJE_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-010_DOBROVOLNIK_OSOBNI_UDAJE_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  10
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-011',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-011',
  'Pracovník / mentor - mlčenlivost',
  'v1.3',
  'RAI-FRM-GDPR-011_PRACOVNIK_MENTOR_MLCENLIVOST_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-011_PRACOVNIK_MENTOR_MLCENLIVOST_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  11
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-012',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-012',
  'Partner / externí subjekt',
  'v1.3',
  'RAI-FRM-GDPR-012_PARTNER_EXTERNI_SUBJEKT_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-012_PARTNER_EXTERNI_SUBJEKT_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  12
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-013',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-013',
  'Odvolání nebo omezení souhlasu',
  'v1.3',
  'RAI-FRM-GDPR-013_ODVOLANI_NEBO_OMEZENI_SOUHLASU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-013_ODVOLANI_NEBO_OMEZENI_SOUHLASU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  13
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-014',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-014',
  'Žádost subjektu údajů',
  'v1.3',
  'RAI-FRM-GDPR-014_ZADOST_SUBJEKTU_UDAJU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-014_ZADOST_SUBJEKTU_UDAJU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  14
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-015',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-015',
  'Záznam o incidentu',
  'v1.3',
  'RAI-FRM-GDPR-015_ZAZNAM_O_INCIDENTU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-015_ZAZNAM_O_INCIDENTU_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  15
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-016',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-016',
  'Anonymizační a donor/export karta',
  'v1.3',
  'RAI-FRM-GDPR-016_ANONYMIZACNI_DONOR_EXPORT_KARTA_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-016_ANONYMIZACNI_DONOR_EXPORT_KARTA_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  16
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-GDPR-017',
  'GDPR',
  '01_GDPR_A_SOUHLASY',
  'GDPR a souhlasy',
  'RAI-FRM-GDPR-017',
  'Archivace, skartace a přístupy',
  'v1.3',
  'RAI-FRM-GDPR-017_ARCHIVACE_SKARTACE_PRISTUPY_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/01_GDPR_A_SOUHLASY/RAI-FRM-GDPR-017_ARCHIVACE_SKARTACE_PRISTUPY_FILLABLE_v1_3_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'GDPR formulář s přiděleným ID a čárovým kódem | barcode_release_v1_2',
  17
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-KLI-001',
  'KLI',
  '02_KLIENTSKA_SLOZKA',
  'Klientská složka',
  'RAI-FRM-KLI-001',
  'Intake form',
  'v1.5',
  'RAI-FRM-KLI-001_INTAKE_FORM_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/02_KLIENTSKA_SLOZKA/RAI-FRM-KLI-001_INTAKE_FORM_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'nan | barcode_release_v1_2',
  18
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-KLI-002',
  'KLI',
  '02_KLIENTSKA_SLOZKA',
  'Klientská složka',
  'RAI-FRM-KLI-002',
  'Kniha klienta',
  'v1.6',
  'RAI-FRM-KLI-002_KNIHA_KLIENTA_FILLABLE_v1_6_COMPACT_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/02_KLIENTSKA_SLOZKA/RAI-FRM-KLI-002_KNIHA_KLIENTA_FILLABLE_v1_6_COMPACT_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'nan | barcode_release_v1_2',
  19
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-KLI-003',
  'KLI',
  '02_KLIENTSKA_SLOZKA',
  'Klientská složka',
  'RAI-FRM-KLI-003',
  'Exit form',
  'v1.5',
  'RAI-FRM-KLI-003_EXIT_FORM_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/02_KLIENTSKA_SLOZKA/RAI-FRM-KLI-003_EXIT_FORM_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'nan | barcode_release_v1_2',
  20
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-JB-001',
  'JB',
  '09_PROGRAMOVE_PRILOHY',
  'Programové přílohy',
  'RAI-FRM-JB-001',
  'JAILBREAK dotazník',
  'v1.5',
  'RAI-FRM-JB-001_JAILBREAK_DOTAZNIK_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/09_PROGRAMOVE_PRILOHY/RAI-FRM-JB-001_JAILBREAK_DOTAZNIK_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'Doplněno ve v1.1 | barcode_release_v1_2',
  21
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-INT-001',
  'INT',
  '03_INTERVENCE',
  'Intervence',
  'RAI-FRM-INT-001',
  'Kniha intervencí',
  'v1.5',
  'RAI-FRM-INT-001_KNIHA_INTERVENCI_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/03_INTERVENCE/RAI-FRM-INT-001_KNIHA_INTERVENCI_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'nan | barcode_release_v1_2',
  22
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-KRZ-001',
  'KRZ',
  '04_KRIZOVY_REZIM',
  'Krizový režim',
  'RAI-FRM-KRZ-001',
  'Kniha krizových intervencí',
  'v1.5',
  'RAI-FRM-KRZ-001_KNIHA_KRIZOVYCH_INTERVENCI_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/04_KRIZOVY_REZIM/RAI-FRM-KRZ-001_KNIHA_KRIZOVYCH_INTERVENCI_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'restricted',
  'active',
  1,
  0,
  'nan | barcode_release_v1_2',
  23
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-KRZ-002',
  'KRZ',
  '04_KRIZOVY_REZIM',
  'Krizový režim',
  'RAI-FRM-KRZ-002',
  'Krizový formulář',
  'v1.5',
  'RAI-FRM-KRZ-002_KRIZOVY_FORMULAR_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/04_KRIZOVY_REZIM/RAI-FRM-KRZ-002_KRIZOVY_FORMULAR_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'restricted',
  'active',
  1,
  0,
  'Převedeno podle finálních pravidel v1.5 | barcode_release_v1_2',
  24
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-EVA-001',
  'EVA',
  '05_EVALUACE_A_FOLLOW_UP',
  'Evaluace a follow-up',
  'RAI-FRM-EVA-001',
  'Stabilizační index',
  'v1.5',
  'RAI-FRM-EVA-001_STABILIZACNI_INDEX_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/05_EVALUACE_A_FOLLOW_UP/RAI-FRM-EVA-001_STABILIZACNI_INDEX_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  1,
  'Exportovat anonymizovaně | barcode_release_v1_2',
  25
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-EVA-002',
  'EVA',
  '05_EVALUACE_A_FOLLOW_UP',
  'Evaluace a follow-up',
  'RAI-FRM-EVA-002',
  'Follow-up tracking',
  'v1.5',
  'RAI-FRM-EVA-002_FOLLOW_UP_TRACKING_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/05_EVALUACE_A_FOLLOW_UP/RAI-FRM-EVA-002_FOLLOW_UP_TRACKING_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  1,
  'Exportovat anonymizovaně | barcode_release_v1_2',
  26
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-ETY-001',
  'ETY',
  '07_ETIKA_A_TYM',
  'Etika a tým',
  'RAI-FRM-ETY-001',
  'Mlčenlivost a etický závazek týmu',
  'v1.5',
  'RAI-FRM-ETY-001_MLCENLIVOST_ETICKY_ZAVAZEK_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/07_ETIKA_A_TYM/RAI-FRM-ETY-001_MLCENLIVOST_ETICKY_ZAVAZEK_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'nan | barcode_release_v1_2',
  27
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-REG-001',
  'REG',
  '06_REGISTRY',
  'Registry',
  'RAI-FRM-REG-001',
  'Registr dobrovolníků',
  'v1.5',
  'RAI-FRM-REG-001_REGISTR_DOBROVOLNIKU_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/06_REGISTRY/RAI-FRM-REG-001_REGISTR_DOBROVOLNIKU_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'Registry v1.7 | barcode_release_v1_2',
  28
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-REG-002',
  'REG',
  '06_REGISTRY',
  'Registry',
  'RAI-FRM-REG-002',
  'Evidence komunitních aktivit',
  'v1.5',
  'RAI-FRM-REG-002_EVIDENCE_KOMUNITNICH_AKTIVIT_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/06_REGISTRY/RAI-FRM-REG-002_EVIDENCE_KOMUNITNICH_AKTIVIT_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'Registry v1.7 | barcode_release_v1_2',
  29
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-REG-003',
  'REG',
  '06_REGISTRY',
  'Registry',
  'RAI-FRM-REG-003',
  'Registr partnerů',
  'v1.5',
  'RAI-FRM-REG-003_REGISTR_PARTNERU_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/06_REGISTRY/RAI-FRM-REG-003_REGISTR_PARTNERU_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'Registry v1.7 | barcode_release_v1_2',
  30
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-REG-004',
  'REG',
  '06_REGISTRY',
  'Registry',
  'RAI-FRM-REG-004',
  'Registr rizik',
  'v1.5',
  'RAI-FRM-REG-004_REGISTR_RIZIK_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/06_REGISTRY/RAI-FRM-REG-004_REGISTR_RIZIK_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'Registry v1.7 | barcode_release_v1_2',
  31
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-REG-005',
  'REG',
  '06_REGISTRY',
  'Registry',
  'RAI-FRM-REG-005',
  'Registr stížností',
  'v1.5',
  'RAI-FRM-REG-005_REGISTR_STIZNOSTI_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/06_REGISTRY/RAI-FRM-REG-005_REGISTR_STIZNOSTI_FILLABLE_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'high',
  'active',
  1,
  0,
  'Registry v1.7 | barcode_release_v1_2',
  32
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-AIO-REG-001',
  'AIO',
  '99_ALL_IN_ONE_VOLITELNE',
  'ALL-IN-ONE volitelné',
  'RAI-AIO-REG-001',
  'Registry ALL-IN-ONE',
  'v1.7',
  'RAI-AIO-REG-001_REGISTRY_ALL_IN_ONE_v1_7_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/99_ALL_IN_ONE_VOLITELNE/RAI-AIO-REG-001_REGISTRY_ALL_IN_ONE_v1_7_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  1,
  'internal',
  'active',
  0,
  0,
  'Volitelný souhrnný PDF balík | barcode_release_v1_2',
  33
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-DOP-001',
  'DOP',
  '08_DOPLNKOVE_LISTY',
  'Doplňkové listy',
  'RAI-FRM-DOP-001',
  'List incidentů',
  'v1.7',
  'RAI-FRM-DOP-001_LIST_INCIDENTU_A4_LANDSCAPE_FILLABLE_v1_7_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/08_DOPLNKOVE_LISTY/RAI-FRM-DOP-001_LIST_INCIDENTU_A4_LANDSCAPE_FILLABLE_v1_7_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'Doplňkový A4 landscape list | barcode_release_v1_2',
  34
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-FRM-DOP-002',
  'DOP',
  '08_DOPLNKOVE_LISTY',
  'Doplňkové listy',
  'RAI-FRM-DOP-002',
  'List hranic podpory',
  'v1.7',
  'RAI-FRM-DOP-002_LIST_HRANIC_PODPORY_A4_LANDSCAPE_FILLABLE_v1_7_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/08_DOPLNKOVE_LISTY/RAI-FRM-DOP-002_LIST_HRANIC_PODPORY_A4_LANDSCAPE_FILLABLE_v1_7_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  0,
  'internal',
  'active',
  1,
  0,
  'Doplňkový A4 landscape list | barcode_release_v1_2',
  35
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-AIO-DOP-001',
  'AIO',
  '99_ALL_IN_ONE_VOLITELNE',
  'ALL-IN-ONE volitelné',
  'RAI-AIO-DOP-001',
  'Doplňkové listy ALL-IN-ONE',
  'v1.7',
  'RAI-AIO-DOP-001_DOPLNKOVE_LISTY_INCIDENTY_HRANICE_ALL_IN_ONE_v1_7_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/99_ALL_IN_ONE_VOLITELNE/RAI-AIO-DOP-001_DOPLNKOVE_LISTY_INCIDENTY_HRANICE_ALL_IN_ONE_v1_7_CONTENT_LOCKED.pdf',
  'pdf',
  1,
  1,
  'internal',
  'active',
  0,
  0,
  'Volitelný souhrnný PDF balík | barcode_release_v1_2',
  36
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-DOC-PROJ-001',
  'DOC',
  '10_METODIKY_A_PODKLADY',
  'Metodiky a podklady',
  'RAI-DOC-PROJ-001',
  'One-page projektu',
  'v1.5',
  'RAI-DOC-PROJ-001_ONE_PAGE_PROJEKT_2026_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/10_METODIKY_A_PODKLADY/RAI-DOC-PROJ-001_ONE_PAGE_PROJEKT_2026_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  0,
  0,
  'public',
  'active',
  0,
  1,
  'Veřejný/partnerský podklad | barcode_release_v1_2',
  37
);
INSERT INTO rest_art_document_files (release_id, form_uid, form_group, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (
  @release_id,
  'RAI-MET-JB-001',
  'MET',
  '10_METODIKY_A_PODKLADY',
  'Metodiky a podklady',
  'RAI-MET-JB-001',
  'Metodika JAILBREAK',
  'v1.5',
  'RAI-MET-JB-001_METODIKA_JAILBREAK_v1_5_CONTENT_LOCKED.pdf',
  '/storage/rest_art/releases/v1_2_barcode/10_METODIKY_A_PODKLADY/RAI-MET-JB-001_METODIKA_JAILBREAK_v1_5_CONTENT_LOCKED.pdf',
  'pdf',
  0,
  0,
  'internal',
  'active',
  0,
  0,
  'Metodický podklad | barcode_release_v1_2',
  38
);