-- REST||ART INTEGRACE - import dokumentů pro programové dotazníky v2.0 RC1
-- Před importem spusťte release insert nebo nastavte @release_id ručně.
SET @release_id := (SELECT id FROM rest_art_document_releases WHERE release_code = 'REST_ART_PROGRAMOVE_DOTAZNIKY_V2_0_RC1' ORDER BY id DESC LIMIT 1);

INSERT INTO rest_art_document_files (release_id, form_uid, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (@release_id, 'RAI-FRM-JB-001', '01_PROGRAMOVE_DOTAZNIKY', 'Programové dotazníky v2.0', 'RAI-FRM-JB-001', 'JAILBREAK - DOTAZNÍK REINTEGRACE PO VTOS', 'v2.0 RC1', 'RAI-FRM-JB-001_JAILBREAK_DOTAZNIK_REINTEGRACE_PO_VTOS_v2_0_RC1_POPPINS_FILLABLE.pdf', '/storage/rest_art/releases/v2_0_rc1/RAI-FRM-JB-001_JAILBREAK_DOTAZNIK_REINTEGRACE_PO_VTOS_v2_0_RC1_POPPINS_FILLABLE.pdf', 'pdf', 1, 0, 'high', 'test_ready', 1, 1, 'JAILBREAK / 159 polí / 16 stran / barcode RAI-FRM-JB-001', 10);
INSERT INTO rest_art_document_files (release_id, form_uid, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (@release_id, 'RAI-FRM-RESET-001', '01_PROGRAMOVE_DOTAZNIKY', 'Programové dotazníky v2.0', 'RAI-FRM-RESET-001', 'RESET - DOTAZNÍK ABSTINENCE A STABILIZACE', 'v2.0 RC1', 'RAI-FRM-RESET-001_RESET_DOTAZNIK_ABSTINENCE_A_STABILIZACE_v2_0_RC1_POPPINS_FILLABLE.pdf', '/storage/rest_art/releases/v2_0_rc1/RAI-FRM-RESET-001_RESET_DOTAZNIK_ABSTINENCE_A_STABILIZACE_v2_0_RC1_POPPINS_FILLABLE.pdf', 'pdf', 1, 0, 'high', 'test_ready', 1, 1, 'RESET / 160 polí / 16 stran / barcode RAI-FRM-RESET-001', 20);
INSERT INTO rest_art_document_files (release_id, form_uid, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (@release_id, 'RAI-FRM-REWORK-001', '01_PROGRAMOVE_DOTAZNIKY', 'Programové dotazníky v2.0', 'RAI-FRM-REWORK-001', 'REWORK - DOTAZNÍK PRACOVNÍ PŘIPRAVENOSTI', 'v2.0 RC1', 'RAI-FRM-REWORK-001_REWORK_DOTAZNIK_PRACOVNI_PRIPRAVENOSTI_v2_0_RC1_POPPINS_FILLABLE.pdf', '/storage/rest_art/releases/v2_0_rc1/RAI-FRM-REWORK-001_REWORK_DOTAZNIK_PRACOVNI_PRIPRAVENOSTI_v2_0_RC1_POPPINS_FILLABLE.pdf', 'pdf', 1, 0, 'high', 'test_ready', 1, 1, 'REWORK / 161 polí / 16 stran / barcode RAI-FRM-REWORK-001', 30);
INSERT INTO rest_art_document_files (release_id, form_uid, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (@release_id, 'RAI-FRM-SW-001', '01_PROGRAMOVE_DOTAZNIKY', 'Programové dotazníky v2.0', 'RAI-FRM-SW-001', 'STREETWISE - DOTAZNÍK TERÉNNÍ PODPORY', 'v2.0 RC1', 'RAI-FRM-SW-001_STREETWISE_DOTAZNIK_TERENNI_PODPORY_v2_0_RC1_POPPINS_FILLABLE.pdf', '/storage/rest_art/releases/v2_0_rc1/RAI-FRM-SW-001_STREETWISE_DOTAZNIK_TERENNI_PODPORY_v2_0_RC1_POPPINS_FILLABLE.pdf', 'pdf', 1, 0, 'high', 'test_ready', 1, 1, 'STREETWISE / 161 polí / 16 stran / barcode RAI-FRM-SW-001', 40);
INSERT INTO rest_art_document_files (release_id, form_uid, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (@release_id, 'RAI-FRM-STAB-001', '01_PROGRAMOVE_DOTAZNIKY', 'Programové dotazníky v2.0', 'RAI-FRM-STAB-001', 'STABILIZACE - DOTAZNÍK UDRŽENÍ ZMĚNY', 'v2.0 RC1', 'RAI-FRM-STAB-001_STABILIZACE_DOTAZNIK_UDRZENI_ZMENY_v2_0_RC1_POPPINS_FILLABLE.pdf', '/storage/rest_art/releases/v2_0_rc1/RAI-FRM-STAB-001_STABILIZACE_DOTAZNIK_UDRZENI_ZMENY_v2_0_RC1_POPPINS_FILLABLE.pdf', 'pdf', 1, 0, 'high', 'test_ready', 1, 1, 'STABILIZACE / 161 polí / 16 stran / barcode RAI-FRM-STAB-001', 50);
INSERT INTO rest_art_document_files (release_id, form_uid, category_code, category_title, document_code, title, version, file_name, file_path, file_type, is_fillable, is_all_in_one, sensitivity, status, crm_use, reporting_export, notes, sort_order) VALUES (@release_id, 'RAI-FRM-BZ-001', '01_PROGRAMOVE_DOTAZNIKY', 'Programové dotazníky v2.0', 'RAI-FRM-BZ-001', 'BOD ZLOMU - DOTAZNÍK MLADÝCH V RIZIKU', 'v2.0 RC1', 'RAI-FRM-BZ-001_BOD_ZLOMU_DOTAZNIK_MLADYCH_V_RIZIKU_v2_0_RC1_POPPINS_FILLABLE.pdf', '/storage/rest_art/releases/v2_0_rc1/RAI-FRM-BZ-001_BOD_ZLOMU_DOTAZNIK_MLADYCH_V_RIZIKU_v2_0_RC1_POPPINS_FILLABLE.pdf', 'pdf', 1, 0, 'high', 'test_ready', 1, 1, 'BOD ZLOMU / 161 polí / 16 stran / barcode RAI-FRM-BZ-001', 60);
